"""
Protocol definitions cho layer repository, phục vụ Clean Architecture/Hexagonal.
Các concrete repo (user_repository, role_repository, ...) chỉ cần thực thi các hàm này.
"""
from __future__ import annotations

from typing import Protocol, List, Optional, Tuple, Iterable, Any, ContextManager


class ConnContext(Protocol):
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def cursor(self, *args, **kwargs): ...


class UserRepoProtocol(Protocol):
    def get_by_username(self, username: str): ...
    def update_last_signon(self, user_id: int): ...
    def insert_user(self, username: str, password_hash, name_display: str): ...
    def get_username(self, user_id: int) -> Optional[str]: ...
    def add_roles(self, user_id: int, role_ids: List[int]): ...
    def set_data_permission(self, user_id: int, permission_id: int): ...
    def list_users(self, where_sql: str, params: List, limit: int, offset: int): ...
    def get_user_info(self, user_id: int, extra_condition: str, params: List): ...
    def replace_user_roles(self, user_id: int, role_ids: List[int]): ...


class RoleRepoProtocol(Protocol):
    def insert_role(self, code: str, description: Optional[str], permissions: List[int]): ...
    def update_role(self, role_id, description: Optional[str], permissions: List[int]): ...
    def delete_role(self, role_id): ...
    def list_roles(self, where_sql: str, params: List, limit: int, offset: int): ...
    def list_public_roles(self, where_sql: str, params: List, limit: int, offset: int): ...
    def get_role(self, role_id, extra_condition: str, params: List): ...
    def list_permissions_of_role(self, role_id): ...
    def list_role_permissions(self, where_sql: str, params: List, limit: int, offset: int): ...
    def list_roles_of_permission(self, permission_id): ...

class PermissionRepoProtocol(Protocol):
    def list_data_set_by_user(self, uid: int): ...
    def list_dataset_by_permission(self, pid: int): ...
    def get_permission_info(self, ids: List[int], extra_condition: str, params: List): ...
    def insert_permission(self, code: str, ptype: str, description: Optional[str], url_list: Iterable, data_sets: Iterable): ...
    def get_permission_type(self, pid: int): ...
    def update_permission(self, pid: int, description: Optional[str], ptype: str, url_list: Iterable, data_sets: Iterable): ...
    def delete_permission(self, pid: int): ...
    def list_permissions(self, where_sql: str, params: List, limit: int, offset: int): ...
    def list_public_data_permissions(self, where_sql: str, params: List, limit: int, offset: int): ...
    def list_url_by_permission(self, pid: int): ...
    def list_urls_by_permissions(self, perm_ids: List[int], perm_codes: List[str]): ...
    def list_pages_by_user(self, uid: int): ...

class SetRepoProtocol(Protocol):
    def list_sets(self, where_sql: str, params: List): ...
    def insert_set(self, payload: dict): ...
    def ensure_set(self, payload: dict, cur=None): ...
    def update_set(self, set_id: int, payload: dict): ...
    def delete_set(self, sid: int): ...
    def list_dataset_by_set(self, sid: int): ...
    def replace_dataset_for_set(self, sid: int, items: List[dict]): ...
    def conn(self) -> ConnContext: ...


class AccessRequestRepoProtocol(Protocol):
    def create_request(self, requester_id: int, requester_username: str, request_type: str, reason: str, ttl_hours: Optional[int]): ...
    def add_items(self, req_id: int, items: List[dict]): ...
    def log_action(self, request_id: int, actor_id: int, action: str, note: Optional[str] = None): ...
    def conn(self) -> ConnContext: ...
    def list_requests(self, where_sql: str, params: List, limit: int, offset: int): ...
    def get_request_with_items(self, req_id: int): ...
    def reject_request(self, req_id: int, actor_id: int, note: str): ...
    def cancel_request(self, req_id: int, actor_id: int): ...
