"""empty message

Revision ID: 1c98efef6428
Revises: 
Create Date: 2022-07-25 18:43:37.540007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c98efef6428'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BU',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xCode', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=150), nullable=True),
    sa.Column('LastUpdateUserName', sa.String(length=50), nullable=True),
    sa.Column('LastUpdateDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xCode'),
    schema='uaa'
    )
    op.create_table('DataPermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('PermissionId', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=100), nullable=True),
    sa.Column('LastUpdateUserName', sa.String(length=50), nullable=True),
    sa.Column('LastUpdateDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='uaa'
    )
    op.create_table('DataSet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DataPermissionId', sa.Integer(), nullable=False),
    sa.Column('SetId', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=100), nullable=True),
    sa.Column('LastUpdateUserName', sa.String(length=50), nullable=True),
    sa.Column('LastUpdateDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='uaa'
    )
    op.create_table('PermissionDefine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('PermissionType', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=150), nullable=True),
    sa.Column('LastUpdateUserName', sa.String(length=50), nullable=True),
    sa.Column('LastUpdateDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Code'),
    schema='uaa'
    )
    op.create_table('RoleDefine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=150), nullable=True),
    sa.Column('LastUpdateUserName', sa.String(length=50), nullable=True),
    sa.Column('LastUpdateDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Code'),
    schema='uaa'
    )
    op.create_table('RolePermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.Column('PermissionId', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=100), nullable=True),
    sa.Column('LastUpdateUserName', sa.String(length=50), nullable=True),
    sa.Column('LastUpdateDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='uaa'
    )
    op.create_table('SetTbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('EFFFDate', sa.Date(), nullable=True),
    sa.Column('EFFTDate', sa.Date(), nullable=True),
    sa.Column('BUId', sa.Integer(), nullable=True),
    sa.Column('Type', sa.String(length=10), nullable=True),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=150), nullable=True),
    sa.Column('LastUpdateUserName', sa.String(length=50), nullable=True),
    sa.Column('LastUpdateDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Code'),
    schema='uaa'
    )
    op.create_table('URLPermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PermissionId', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=150), nullable=False),
    sa.Column('EFFFDate', sa.Date(), nullable=True),
    sa.Column('EFFTDate', sa.Date(), nullable=True),
    sa.Column('Method', sa.String(length=10), nullable=True),
    sa.Column('Description', sa.String(length=100), nullable=True),
    sa.Column('Type', sa.String(length=10), nullable=True),
    sa.Column('LastUpdateUserName', sa.String(length=50), nullable=True),
    sa.Column('LastUpdateDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='uaa'
    )
    op.create_table('UserDefine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=50), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=True),
    sa.Column('Password', sa.LargeBinary(length=500), nullable=False),
    sa.Column('UserLocked', sa.Boolean(), nullable=True),
    sa.Column('NameDisplay', sa.String(length=100), nullable=True),
    sa.Column('LastSignOnDateTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateUserName', sa.String(length=50), nullable=True),
    sa.Column('LastUpdateDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('UserName'),
    schema='uaa'
    )
    op.create_table('UserRole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=100), nullable=True),
    sa.Column('LastUpdateUserName', sa.String(length=50), nullable=True),
    sa.Column('LastUpdateDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='uaa'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserRole', schema='uaa')
    op.drop_table('UserDefine', schema='uaa')
    op.drop_table('URLPermission', schema='uaa')
    op.drop_table('SetTbl', schema='uaa')
    op.drop_table('RolePermission', schema='uaa')
    op.drop_table('RoleDefine', schema='uaa')
    op.drop_table('PermissionDefine', schema='uaa')
    op.drop_table('DataSet', schema='uaa')
    op.drop_table('DataPermission', schema='uaa')
    op.drop_table('BU', schema='uaa')
    # ### end Alembic commands ###
