port 0
tls-port 6380
tls-cert-file /certs/redis.crt
tls-key-file /certs/redis.key
tls-ca-cert-file /certs/ca.crt
# Nếu muốn client phải trình CA, đổi thành "yes"
tls-auth-clients no
requirepass 123456@